name: core_image_editor
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  args: ^2.7.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  provider: ^6.1.2
  universal_html: ^2.2.4
  widgets_to_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: English
      fonts:
        - asset: assets/fonts/English.ttf
    - family: Lohit-Assamese
      fonts:
        - asset: assets/fonts/Lohit-Assamese.ttf
    - family: Lohit-Bengali
      fonts:
        - asset: assets/fonts/Lohit-Bengali.ttf
    - family: Lohit-Devanagari
      fonts:
        - asset: assets/fonts/Lohit-Devanagari.ttf
    - family: Lohit-Gujarati
      fonts:
        - asset: assets/fonts/Lohit-Gujarati.ttf
    - family: Lohit-Kannada
      fonts:
        - asset: assets/fonts/Lohit-Kannada.ttf
    - family: Lohit-Malayalam
      fonts:
        - asset: assets/fonts/Lohit-Malayalam.ttf
    - family: Lohit-Marathi
      fonts:
        - asset: assets/fonts/Lohit-Marathi.ttf
    - family: Lohit-Oriya
      fonts:
        - asset: assets/fonts/Lohit-Oriya.ttf
    - family: Lohit-Punjabi
      fonts:
        - asset: assets/fonts/Lohit-Punjabi.ttf
    - family: Lohit-Tamil
      fonts:
        - asset: assets/fonts/Lohit-Tamil.ttf
    - family: Lohit-Telugu
      fonts:
        - asset: assets/fonts/Lohit-Telugu.ttf
    - family: Noto-Urdu
      fonts:
        - asset: assets/fonts/Noto-Urdu.ttf

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
